-- ── Restaurant Tools (server) ────────────────────────────────────────────────
-- Validates the ace permission and prints generated code to server console.
-- hasBuilderAccess is also exposed as a plain export so other resources
-- (e.g. pl_burgershot's own dev-only test commands) can gate on the same
-- permission without duplicating the ace-check.

lib.callback.register(ResourceEvent('hasBuilderAccess'), function(source)
    return IsPlayerAceAllowed(tostring(source), Config.AcePermission)
end)

exports('hasBuilderAccess', function(src)
    return IsPlayerAceAllowed(tostring(src), Config.AcePermission)
end)

RegisterNetEvent(ResourceEvent('locationbuilder:output'))
AddEventHandler(ResourceEvent('locationbuilder:output'), function(code)
    local src = source
    if not IsPlayerAceAllowed(tostring(src), Config.AcePermission) then return end
    if type(code) ~= 'string' or #code > 8000 then return end
    print(('\n%s\n[Restaurant Tools] Location Builder — generated by %s — paste into Location.Management in location.lua:\n%s\n%s\n')
        :format(('='):rep(60), GetPlayerName(src), code, ('='):rep(60)))
end)

RegisterNetEvent(ResourceEvent('chairbuilder:output'))
AddEventHandler(ResourceEvent('chairbuilder:output'), function(code)
    local src = source
    if not IsPlayerAceAllowed(tostring(src), Config.AcePermission) then return end
    if type(code) ~= 'string' or #code > 8000 then return end
    print(('\n%s\n[Restaurant Tools] Chair Builder — generated by %s — paste into Location.ChairGroups in location.lua:\n%s\n%s\n')
        :format(('='):rep(60), GetPlayerName(src), code, ('='):rep(60)))
end)

RegisterNetEvent(ResourceEvent('tablebuilder:output'))
AddEventHandler(ResourceEvent('tablebuilder:output'), function(code)
    local src = source
    if not IsPlayerAceAllowed(tostring(src), Config.AcePermission) then return end
    if type(code) ~= 'string' or #code > 8000 then return end
    print(('\n%s\n[Restaurant Tools] Table Builder — generated by %s — paste into Location.Tables in location.lua:\n%s\n%s\n')
        :format(('='):rep(60), GetPlayerName(src), code, ('='):rep(60)))
end)

RegisterNetEvent(ResourceEvent('propplacer:output'))
AddEventHandler(ResourceEvent('propplacer:output'), function(model, code)
    local src = source
    if not IsPlayerAceAllowed(tostring(src), Config.AcePermission) then return end
    if type(code) ~= 'string' or #code > 8000 then return end
    if type(model) ~= 'string' or #model > 200 then model = '?' end
    print(('\n%s\n[Restaurant Tools] Prop Placer — generated by %s for "%s":\n    %s\n%s\n')
        :format(('='):rep(60), GetPlayerName(src), model, code, ('='):rep(60)))
end)

RegisterNetEvent(ResourceEvent('propattach:output'))
AddEventHandler(ResourceEvent('propattach:output'), function(model, boneId, code)
    local src = source
    if not IsPlayerAceAllowed(tostring(src), Config.AcePermission) then return end
    if type(code) ~= 'string' or #code > 8000 then return end
    if type(model) ~= 'string' or #model > 200 then model = '?' end
    if type(boneId) ~= 'number' then boneId = -1 end
    print(('\n%s\n[Restaurant Tools] Prop Attachment Tool — generated by %s for "%s" on bone %d:\n    %s\n%s\n')
        :format(('='):rep(60), GetPlayerName(src), model, boneId, code, ('='):rep(60)))
end)
